external_templates:
  repo: templates
  template_variables:
    collection_section: "01"
    default:
      image: chart/<<key_name_encoded>>

collections:
  Trending Movies:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-movies-top-20
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    summary: Trending movies from the internet listing from release date.
    template:
      - name: chart_shared
        key: trending_movies

  Internet's Most Popular:
    mdblist_list: https://mdblist.com/lists/drazzilb/top-200-movies
    smart_label:
      sort_by: random
      all:
        label: <<smart_label>>
    summary: The internet's most popular movies from the last 10 years sorted by rank.
    template:
      - name: chart_shared
        key: popular_movies