external_templates:
  repo: templates
  template_variables:
    collection_section: "01"
    image: chart/<<mapping_name_encoded>>



templates:
  mal:
    default:
      limit: 100
      limit_<<key>>: <<limit>>
      chart: <<key>>
    mal_<<chart>>: <<limit_<<key>>>>

  season:
    default:
      limit: 100
      limit_season: <<limit>>
    mal_season:
      season: current
      sort_by: score
      limit: <<limit_season>>

collections:
  MyAnimeList Popular:
    variables:
      key: popular
    template:
      - name: mal
      - name: shared
      - name: arr
      - name: custom

  MyAnimeList Favorited:
    variables:
      key: favorited
    template:
      - name: mal
        chart: favorite
      - name: shared
      - name: arr
      - name: custom


  MyAnimeList Top Rated:
    variables:
      key: top
    template:
      - name: mal
        chart: all
      - name: shared
      - name: arr
      - name: custom


  MyAnimeList Top Airing:
    variables:
      key: airing
    template:
      - name: mal
      - name: shared
      - name: arr
      - name: custom


  MyAnimeList Season:
    variables:
      key: season
    template:
      - name: season
      - name: shared
      - name: arr
      - name: custom
