#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - repo: PMM/chart/other                              #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   stevenlu         StevenLu's Popular Movies   #
#          #   anidb            AniDB Popular               #
#          #   pirated          Top 10 Pirated Movies       #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          radarr_add_missing_key:                          #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

external_templates:
  repo: templates
  template_variables:
    collection_section: "01"

collections:
  AniDB Popular:
    summary: A collection of Popular Anime on AniDB
    anidb_popular: 30
    template:
      - name: customsync
      - name: chart_shared
        key: anidb

  Trending Movies:
    mdblist_list: 
      url: https://mdblist.com/lists/drazzilb/trending-movies-top-20
    smart_label: release.desc
    summary: Trending movies from the internet listing from release date.
    template:
      - name: chart_shared
        key: trending_movies

  Internet's Most Popular:
    mdblist_list: 
      url: https://mdblist.com/lists/drazzilb/top-200-movies
    smart_label: rank.desc
    summary: The internet's most popular movies from the last 10 years sorted by rank.
    template:
      - name: chart_shared
        key: popular_movies

  Trending Animated Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-animated-shows-50
    summary: Trending animated shows collected from TheMovieDb and Trakt sorted by release date.
    template:
      - name: customsync
      - name: chart_shared
        key: trending_animated

  Popular Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/popular-shows-50
    summary: Most popular Trakt Popular shows plus mdblist's popular list released in the past 10 years sorted by audiance score.
    template:
      - name: customsync
      - name: chart_shared
        key: popular_series

  Trending Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-shows-20
    summary: Trending shows from Trakt Trending rated above 50 sorted by release date.
    template:
      - name: customsync
      - name: chart_shared
        key: trending_series
