
external_templates:
  repo: templates
  template_variables:
    collection_section: "01"

collections:
  AniDB Popular:
    summary: A collection of Popular Anime on AniDB
    anidb_popular: 30
    template:
      - name: customsync
      - name: chart_shared
        key: anidb

  Trending Movies:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-movies-top-20
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    summary: Trending movies from the internet listing from release date.
    template:
      - name: chart_shared
        key: trending_movies

  Internet's Most Popular:
    mdblist_list: https://mdblist.com/lists/drazzilb/top-200-movies
    smart_label:
      sort_by: random
      all:
        label: <<smart_label>>
    summary: The internet's most popular movies from the last 10 years sorted by rank.
    template:
      - name: chart_shared
        key: popular_movies

  Trending Animated Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-animated-shows-50
    summary: Trending animated shows collected from TheMovieDb and Trakt sorted by release date.
    template:
      - name: customsync
      - name: chart_shared
        key: trending_animated

  Popular Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/popular-shows-50
    summary: Most popular Trakt Popular shows plus mdblist's popular list released in the past 10 years sorted by audiance score.
    template:
      - name: customsync
      - name: chart_shared
        key: popular_series

  Trending Series:
    mdblist_list: https://mdblist.com/lists/drazzilb/trending-shows-20
    summary: Trending shows from Trakt Trending rated above 50 sorted by release date.
    template:
      - name: customsync
      - name: chart_shared
        key: trending_series
